version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-node
      environment:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
    - image: circleci/mysql:5.7-ram
      environment:
        MYSQL_DATABASE: db
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_ROOT_HOST: db
        MYSQL_USER: root
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.0.1
          bundle install --jobs=4 --retry=3 --path vendor/bundle
    - run:
        command: bundle exec rails db:create
    - run:
        command: bundle exec rails db:schema:load
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# jobs:
#  build:
#    docker:
#    - image: circleci/ruby:2.6.3-node
#      environment:
#        RAILS_ENV: test
#        DB_HOST: 127.0.0.1
#    - image: circleci/mysql:5.7-ram
#      environment:
#        MYSQL_DATABASE: db
#        MYSQL_ALLOW_EMPTY_PASSWORD: true
#        MYSQL_ROOT_HOST: db
#        MYSQL_USER: root
#    working_directory: ~/repo
#    steps:
#    - checkout
#    - run:
#       name: install dependencies
#       command: |
#         gem install bundler -v 2.0.1
#         bundle install --jobs=4 --retry=3 --path vendor/bundle
#    - run: bundle exec rails db:create
#    - run: bundle exec rails db:schema:load